[package]
name = "embedded-vintage-fonts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = "0.7.0"
embedded-graphics-simulator = { version = "0.3.0", optional = true }
